### ISSUE TITLE
Kuri disable taking photos

### ISSUE THREAD

**Issue by Carter90** [KuriRobot/Kuri-Documentation#39]
Greetings,
I have a Kuri operating in a learning center with lots of students and some are uncomfortable having their picture taken,
and Kuri's facial recognition is very good and still works even with masks on. 
I know the cloud image storage instance is now down so the images go into oblivion but it would be nice to just disable taking of the pictures. 
I do see in `/opt/gizmo/share/gizmo/configs/kuri_behavior.yaml`
```yaml
wander_photo_shoot_default_time: 60.0  # Defult time for photos at a waypoint
wander_photo_shoot_max_time: 600.0  # Maximum time for photos at a waypoint
wander_photo_shoot_without_moments_time: 180.0  # Max time for photos at a waypoint without any captures
wander_min_seconds_between_captures: 10.0
```
In these configurations should I put massive, small or negative numbers or is there a configuration I'm missing that would be more appropriate  

I've been tempted to mess up the animation calls and see if that works too.

I also see listed in some `SOURCES.txt` reference to `src/gizmo/behavior/hfsm/photo_shoot/photo_shoot_state_machine.py` and `photo_shoot_states.py` but these python files don't seem to be on my Kuri. 

Any advice would be greatly appreciated, thanks.
